name = "miez-mil-gonars"
compatibility_date = "2025-11-19"

# This project deploys via Cloudflare Pages.
# No Workers entrypoint or [site] configuration is needed.
# If you later switch to Workers, reintroduce the proper fields.
pages_build_output_dir = "./"
account_id = "a0592646a2b84958d2b8ab7ec9d1cb74"
